version: '3'
services:
  web:
    image: node:6.0.0
    ports:
      # Needs to be same port for hot reload to work
      - 8080:8080
    command: bash -c "npm run dev"
    working_dir: /webapp
    volumes:
      - ".:/webapp"
    environment:
      # Needs to be set to 0.0.0.0
      - HOST=0.0.0.0
      - PORT=8080